- hosts: new-node
  roles:
  - prepare
  - kubectl
  - docker
  - kube-node
  # 根据hosts中配置，以下两种网络只会安装一种
  - { role: calico, when: "CLUSTER_NETWORK == 'calico'" }
  - { role: flannel, when: "CLUSTER_NETWORK == 'flannel'" }

- hosts: deploy
  tasks:
  - name: 批准新增node节点
    shell: "sleep 15 && {{ bin_dir }}/kubectl get csr|grep 'Pending' | awk 'NR>0{print $1}'| xargs {{ bin_dir }}/kubectl certificate approve"
    ignore_errors: true
